# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title bisection
#' @description Find the target value using the dichotomy method
#' @param x target sequence
#' @param target the target number
#' @return mid target value subscript
#' @examples
#' \dontrun{
#'   x <- seq(1:50)
#'   target <- 8
#'   result <- binarySearchC(x, target)
#'   print(result)
#' }
#' @export
binarySearchC <- function(x, target) {
    .Call('_SA22231050_binarySearchC', PACKAGE = 'SA22231050', x, target)
}

#' @title newton
#' @description Newton's method to find roots
#' @param x0 the init number
#' @param tol the tolerant number
#' @param max_iter the max number of loop
#' @return mid target value subscript
#' @examples
#' \dontrun{
#' x0 <- -9
#' tol <- 1e-6
#' max_iter <- 100
#' result <- newtonMethodC(x0, tol, max_iter)
#' print(result)
#' }
#' @export
newtonMethodC <- function(x0, tol, max_iter) {
    .Call('_SA22231050_newtonMethodC', PACKAGE = 'SA22231050', x0, tol, max_iter)
}

